spring:   application:    name: spring-cloud-config-server  cloud:    config:      server:        git:          uri: file:///D:/Proyectos/Java/Microservicios/did-config-files

server:
  port: 8889
  

eureka:
  client:
    registerWithEureka:  true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
 
      
      
    
    
    